In [1]:
import pandas as pd

In [2]:
#Acess through Index
s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(s[0])
print(s[2])
print(type(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64
1
3
<class 'pandas.Series'>

In [17]:
#Access through Label 
s = pd.Series([1, 2, 3, 4, 5], index=["Adam", "eve", "Bob", "Alice", "Carlie"])
print(s)
print(s["Bob"])
print(s.index)

Adam      1
eve       2
Bob       3
Alice     4
Carlie    5
dtype: int64
3
Index(['Adam', 'eve', 'Bob', 'Alice', 'Carlie'], dtype='str')

In [18]:
#Vectorized Operation
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])

print (s1 + s2)
s1[0] = 100 #Modify the array
print(s1)

changed_s1 = s1.drop(0) #Drop the value from an Array
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
#DataFrame (Object)

info = {
    "Name": ["Adam", "eve", "Bob", "Alice", "Carlie"],
    "Age": [22, 23, 24, 25, 26],
    "Cgpa": [8.9, 9.2, 7.8, 9.7, 8.5]
}

df = pd.DataFrame(info)
print(df, type(df))
print(df.index)
print(df.columns)

     Name  Age  Cgpa
0    Adam   22   8.9
1     eve   23   9.2
2     Bob   24   7.8
3   Alice   25   9.7
4  Carlie   26   8.5 <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=5, step=1)
Index(['Name', 'Age', 'Cgpa'], dtype='str')

In [21]:
#DataFrame (List of Lists)

df = pd.DataFrame([["Vishal", 25], ["Himanshu", 22], ["Nikhil", 18], ["Arjun", 15]], columns=["Name", "Age"])
print(df)

       Name  Age
0    Vishal   25
1  Himanshu   22
2    Nikhil   18
3     Arjun   15

In [22]:
#DataFrame (Numpy Array)
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]]);
df = pd.DataFrame(np_arr, columns=["A", "B", "C"]);
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [23]:
#CSV Data

df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [24]:
#DataFrame Methods
df.head() # Starting 5 rows
df.head(2) # starting particular 2 rows
df.tail() # last 5 rows
df.tail(2) # last 2 particular rows
df.sample() # Show random any row
df.info() # Summary
df.shape # It returns tuple
df.describe()  # It describe all important values
df.columns # it returns table's header
df.nunique() # it returns unique values

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [25]:
#JSON Data

df = pd.read_json("raw_data.json")
print(df, type(df))

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0 <class 'pandas.DataFrame'>

In [5]:
#AQI Dataset

df = pd.read_csv("globalAirQuality.csv")
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [6]:
#Selecting the data

#Columns
df["city"] # CityWise data
df[["city", "aqi"]] # Access multiple columns

#Rows
df.loc[0] #Label wise
df.loc[0:2] # Starting index : Ending Index (inclusive)

df.iloc[0] #Index wise
df.iloc[0:2] # Starting index : Ending Index (Exclusive)

#Cells - Rows & Columns
df.loc[0:2, ["country", "city", 'latitude', 'longitude', "aqi"]]

df.columns
df.iloc[0:3, 1:5]

df.at[0, "city"]
df.iat[0, 2]

df["city"] # View -> Therefore I can't modify it

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str

In [30]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [10]:
#Filtering the Data

df[ df["aqi"] > 100]
df[(df["aqi"] > 100) & (df["temperature"] > 30)]
aqi_data = df[(df["aqi"] > 100) & (df["temperature"] > 30)][["city", "aqi"]]
aqi_data
aqi_data.iloc[0]

city    New York
aqi          155
Name: 6, dtype: object

In [13]:
#Query Rules
df.query("aqi > 100")
df.query("aqi > 100 & temperature > 30")[["city", "aqi"]]
aqi_val = 100
df.query("aqi > @aqi_val & temperature > 30")[["city", "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [13]:
#Cleaning Data - Missing Values
df = pd.read_csv("raw_data.csv")
df.isnull() #It returns "True" in-place of "NaN"
df.isnull().sum() #Count the missing value of each columns
df.dropna() #Drops all the null values from our Dataset as Drops rows wise
df.dropna(axis=1) #Drops all the null values from our Dataset as Drops column wise
df.fillna(0) #Fill the particular value in-place of NaN

age_mean = df["age"].mean()
df["age"].fillna(age_mean)

cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean();
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean);
# cleaned_data

df.ffill # Forward fill
df.bfill() # Backword fill

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [59]:
#Cleaing Data --> Handle De-Duplication
df2 = df.copy()
df2.duplicated()
df2["country"].duplicated()
df2[["country", "gender"]].duplicated()
df2.drop_duplicates(inplace=True)
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [43]:
#Cleaning Data --> Handle Data Types
df.dtypes
df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [57]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data['timestamp'] = pd.to_datetime(aqi_data['timestamp'])
aqi_data["timestamp"].dtypes

dtype('<M8[us]')

In [50]:
date_str = pd.Series([pd.to_datetime("2026-09-12")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [77]:
#Cleaning data -> Handles String
data = pd.read_csv("raw_data.csv")
data["gender"].str.lower()

0        male
1        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: str

In [73]:
data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0